### ISSUE TITLE
Need UI for filters that return "nothing"

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/ontology-ui#110]
if you user creates a set of search filters that return the empty set, we currently print an error on the console and display the entire ontology (see createDag()).

What UI _should_ manifest when filters return the empty set?

**Comment by colinmegill** [comment]
Proposal: 

![Image](https://user-images.githubusercontent.com/1770265/173678700-1f03025a-b5a2-4f4c-9053-2a2139693bb1.png)

**Comment by colinmegill** [comment]
![Image](https://user-images.githubusercontent.com/1770265/202046290-9993193e-2556-44bf-97ba-dad280ae9561.png)
