### ISSUE TITLE
UBERON renders offscreen

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/ontology-ui#87]
UBERON graph offscreen, perhaps because fewer nodes than CL

To reproduce: http://localhost:3000/ontology/UBERON

<img width="2048" alt="Screen Shot 2022-05-04 at 4 08 54 PM" src="https://user-images.githubusercontent.com/1770265/166841391-76073108-327b-403d-8bc9-7b113d290526.png">

**Comment by bkmartinjr** [comment]
OSX RETINA (NOT WORKING): graphDiameter=962.3928511787689, devicePixelRatio=2, nNodes=2315, width=1984, height=1900
ASUS 4k (WORKING): graphDiameter=962.3928511787689, devicePixelRatio=1, nNodes=2315, width=3040, height=1990
